"""
Emit the LaTeX for the ensemble subsection from ensemble_results.json.

Written rather than hand-typed so the paper cannot drift from the measurements,
which is the failure mode that made the original Section 3.8 table untrustworthy.
Output goes to report/ensemble_section.tex, which acl_report.tex \\input's.
"""
import os

import numpy as np

from common import NB_PATH, cpath, load_json, log, setup


def esc(s):
    return s.replace("&", r"\&").replace("%", r"\%").replace("_", r"\_")


def main():
    ens = load_json("ensemble_results.json")
    if not ens:
        raise SystemExit("ensemble_results.json not found - run ensemble.py first")
    test_rows = load_json("test_results.json")
    by_model = {r["Model"]: r for r in test_rows}
    best = ens["best_single_model"]

    S = setup(need_seq=False, need_tfidf=False)["S"]
    y_test = S["y_test"]
    classes = list(S["classes"])

    from sklearn.metrics import f1_score
    z = np.load(cpath("test_predictions.npz"))
    ens_preds = np.load(cpath("ensemble_predictions.npz"))["ensemble"]
    f_ens = f1_score(y_test, ens_preds, average=None, labels=list(range(9)), zero_division=0)
    f_best = f1_score(y_test, z[best], average=None, labels=list(range(9)), zero_division=0)

    L = []
    A = L.append
    A(r"% Generated by pipeline/gen_tex.py -- do not edit by hand.")
    A(r"\subsection{Ensemble of the Best-Performing Models}")
    A(r"\label{sec:ensemble}")
    A("")
    A(f"Section~\\ref{{sec:results}} showed that the three paradigms make "
      f"qualitatively different errors, which is the precondition for a useful "
      f"ensemble. We searched {ens['candidates_evaluated']} candidate combinations "
      f"(hard and soft voting, uniform and validation-F1 weighting, 3--9 members) "
      f"\\textbf{{on the validation split}}, then scored the single winning "
      f"configuration on the test split once. Selecting members by test "
      f"performance would report a gain that does not generalise.")
    A("")
    A(f"The selected system is {esc(ens['scheme'])} voting with "
      f"{esc(ens['weighting'])} weighting over "
      f"{len(ens['members'])} members: "
      + ", ".join(f"\\textbf{{{esc(m)}}}" for m in ens["members"]) + ".")
    A("")

    # Headline table
    A(r"\begin{table}[t]")
    A(r"\centering")
    A(r"\small")
    A(r"\begin{tabular}{lr}")
    A(r"\toprule")
    A(r"\textbf{System} & \textbf{Test Macro F1} \\")
    A(r"\midrule")
    A(f"{esc(best)} (best single) & {ens['best_single_test_macro_f1']:.4f} \\\\")
    A(f"Ensemble & \\textbf{{{ens['test_macro_f1']:.4f}}} \\\\")
    A(r"\midrule")
    A(f"Difference & {ens['delta_pp']:+.2f} pp \\\\")
    A(r"\bottomrule")
    A(r"\end{tabular}")
    A(f"\\caption{{Ensemble versus the best single model. Members were selected on "
      f"validation (macro F1 {ens['val_macro_f1']:.4f}) and the test split was "
      f"scored once.}}")
    A(r"\label{tab:ensemble}")
    A(r"\end{table}")
    A("")

    # Diversity table
    A(r"\begin{table}[t]")
    A(r"\centering")
    A(r"\small")
    A(r"\begin{tabular}{lrr}")
    A(r"\toprule")
    A(r"\textbf{Member} & \textbf{Disagree} & \textbf{Own F1} \\")
    A(r"\midrule")
    for m in ens["members"]:
        if m == best or m not in z.files:
            continue
        dis = float(np.mean(z[m] != z[best])) * 100
        A(f"{esc(m)} & {dis:.1f}\\% & {by_model[m]['Test Macro F1']:.4f} \\\\")
    A(r"\bottomrule")
    A(r"\end{tabular}")
    A(f"\\caption{{Ensemble member diversity: fraction of test documents on which "
      f"each member disagrees with {esc(best)}. Decorrelation, not individual "
      f"strength, is what earns a place in the vote.}}")
    A(r"\label{tab:diversity}")
    A(r"\end{table}")
    A("")

    # Per-class effect, ordered rarest first
    order = sorted(range(9), key=lambda i: int((y_test == i).sum()))
    A(r"\begin{table}[t]")
    A(r"\centering")
    A(r"\small")
    A(r"\begin{tabular}{lrrr}")
    A(r"\toprule")
    A(r"\textbf{Class} & \textbf{" + esc(best) + r"} & \textbf{Ens.} & $\Delta$ \\")
    A(r"\midrule")
    for i in order:
        d = (f_ens[i] - f_best[i]) * 100
        A(f"{esc(classes[i])} & {f_best[i]:.4f} & {f_ens[i]:.4f} & {d:+.2f} \\\\")
    A(r"\bottomrule")
    A(r"\end{tabular}")
    A(r"\caption{Per-class F1, ordered from rarest to most common class.}")
    A(r"\label{tab:ensembleperclass}")
    A(r"\end{table}")
    A("")

    rare = order[:4]
    common = order[-4:]
    rd = float(np.mean([f_ens[i] - f_best[i] for i in rare])) * 100
    cd = float(np.mean([f_ens[i] - f_best[i] for i in common])) * 100
    if rd > cd:
        A(f"The gain concentrates on the rare classes ({rd:+.2f} pp mean over the "
          f"four smallest, against {cd:+.2f} pp over the four largest), which is the "
          f"desirable direction: rare classes are where individual models are least "
          f"confident and a vote has most to correct.")
    else:
        A(f"The gain sits mainly on the common classes ({cd:+.2f} pp mean over the "
          f"four largest, against {rd:+.2f} pp over the four smallest). Ensembling is "
          f"therefore not a substitute for the imbalance handling of "
          f"Section~\\ref{{sec:novelty}}.")
    A("")

    infer = sum(by_model[m]["Inference Time (s)"] for m in ens["members"] if m in by_model)
    bi = by_model[best]["Inference Time (s)"]
    ratio = infer / max(bi, 1e-9)
    overhead = infer - bi
    A(f"An ensemble pays the inference cost of every member: {infer:.1f}\\,s over "
      f"the test set against {bi:.1f}\\,s for {esc(best)} alone "
      f"({ratio:.2f}$\\times$).")
    if ens["delta_pp"] > 0 and ratio < 1.1:
        A("")
        A(f"That overhead is negligible, because the two added members are the "
          f"cheapest models in the study: the ensemble costs {overhead:.1f}\\,s more "
          f"than {esc(best)} alone across 303{{,}}213 documents, a "
          f"{(ratio - 1) * 100:.1f}\\% increase, for {ens['delta_pp']:+.2f} pp of "
          f"Macro F1. Unlike the accuracy/latency trade of "
          f"Table~\\ref{{tab:main}}, there is no trade-off to weigh here: the "
          f"ensemble dominates its strongest member at essentially equal cost.")
    else:
        A("")
        A(f"Three models must then be versioned, loaded and kept in sync rather "
          f"than one, so deployment complexity rises even where wall-clock cost "
          f"does not.")

    out = os.path.join(os.path.dirname(NB_PATH), "report", "ensemble_section.tex")
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(L) + "\n")
    log(f"wrote {out} ({len(L)} lines)")


if __name__ == "__main__":
    main()
